'use client';
import { AnimatePresence, motion } from 'framer-motion';
import { useEffect, useReducer } from 'react';
import type { DraftState, Invitation, InvitationStep } from '@/lib/types';
import { EnvelopeIntro } from './EnvelopeIntro';import { MainQuestion } from './MainQuestion';import { AcceptedReaction } from './AcceptedReaction';import { DateSelector } from './DateSelector';import { ActivitySelector } from './ActivitySelector';import { InvitationSummary } from './InvitationSummary';import { InvitationSuccess } from './InvitationSuccess';import { InvitationDeclined } from './InvitationDeclined';import { InvitationProgress } from './InvitationProgress';import { FloatingDecorations } from './FloatingDecorations';
type Action={type:'GO';step:InvitationStep}|{type:'PATCH';patch:Partial<DraftState>};
const initial:DraftState={step:'closed',selectedActivities:[]};
function reducer(s:DraftState,a:Action):DraftState{return a.type==='GO'?{...s,step:a.step}:{...s,...a.patch}}
export function InvitationShell({invitation}:{invitation:Invitation}){const key=`invite:${invitation.slug}`;const [state,dispatch]=useReducer(reducer,initial,(i)=>{if(typeof sessionStorage==='undefined')return i;try{return {...i,...JSON.parse(sessionStorage.getItem(key)||'{}')}}catch{return i}});useEffect(()=>{sessionStorage.setItem(key,JSON.stringify(state))},[key,state]);useEffect(()=>{fetch(`/api/invitations/${invitation.slug}/open`,{method:'POST'}).catch(()=>undefined)},[invitation.slug]);const go=(step:InvitationStep)=>dispatch({type:'GO',step});const patch=(patch:Partial<DraftState>)=>dispatch({type:'PATCH',patch});return <main data-theme={invitation.theme} className="safe-screen relative grid place-items-center overflow-hidden bg-background p-4"><FloatingDecorations/><section className="relative z-10 flex min-h-[min(760px,92dvh)] w-full max-w-[500px] flex-col rounded-[2rem] border border-line bg-surface/90 p-5 shadow-xl backdrop-blur"><InvitationProgress step={state.step}/><p aria-live="polite" className="sr-only">Текущий экран: {state.step}</p><AnimatePresence mode="wait"><motion.div key={state.step} initial={{opacity:0,y:18}} animate={{opacity:1,y:0}} exit={{opacity:0,y:-18}} transition={{duration:.35}} className="flex flex-1 flex-col justify-center"><Screens invitation={invitation} state={state} go={go} patch={patch}/></motion.div></AnimatePresence></section></main>}
function Screens({invitation,state,go,patch}:{invitation:Invitation;state:DraftState;go:(s:InvitationStep)=>void;patch:(p:Partial<DraftState>)=>void}){if(state.step==='closed')return <EnvelopeIntro intro={invitation.introText} onOpen={()=>go('question')}/>;if(state.step==='question')return <MainQuestion invitation={invitation} onYes={()=>{patch({answer:'accepted'});go('acceptedReaction')}} onNo={()=>{patch({answer:'declined'});go('declined')}}/>;if(state.step==='acceptedReaction')return <AcceptedReaction text={invitation.acceptedText} onContinue={()=>go('date')}/>;if(state.step==='date')return <DateSelector dates={invitation.availableDates} selected={state.selectedDate} onSelect={(d)=>patch({selectedDate:d})} onContinue={()=>go('activity')}/>;if(state.step==='activity')return <ActivitySelector activities={invitation.activities} multi={invitation.multiSelectActivities} selected={state.selectedActivities} onChange={(a)=>patch({selectedActivities:a})} onContinue={()=>go('summary')}/>;if(state.step==='summary')return <InvitationSummary invitation={invitation} state={state} onComment={(comment)=>patch({comment})} onBack={()=>go('activity')} onConfirm={async()=>{await fetch(`/api/invitations/${invitation.slug}/respond`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(state)});go('success')}}/>;if(state.step==='declined')return <InvitationDeclined onBack={()=>go('question')} slug={invitation.slug}/>;return <InvitationSuccess invitation={invitation} state={state}/>}
